### ISSUE TITLE
Calculations of mito directly generate columns with dtypes that break qc calculations on subsequent filtering

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/scanpy-scripts#116]
Running a first filter step (genes or cells) when there are no mito columns given as part of the cell metadata generates a mito column that is considered logical probably by pandas (instead of possibly categorical when read from the metadata file). This leads into the following error:

```
Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/bin/scanpy-filter-genes", line 10, in <module>
    sys.exit(FILTER_CMD())
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scanpy_scripts/cmd_utils.py", line 46, in cmd
    func(adata, **kwargs)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scanpy_scripts/cmd_utils.py", line 288, in matrix_function
    func(
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scanpy_scripts/lib/_filter.py", line 75, in filter_anndata
    sc.pp.calculate_qc_metrics(
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 306, in calculate_qc_metrics
    obs_metrics = describe_obs(
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scanpy/preprocessing/_qc.py", line 123, in describe_obs
    X[:, adata.var[qc_var].values].sum(axis=1)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scipy/sparse/_index.py", line 147, in _validate_indices
    col = self._asindices(col, N)
  File "/usr/local/tools/_conda/envs/__scanpy-scripts@1.1.2/lib/python3.9/site-packages/scipy/sparse/_index.py", line 169, in _asindices
    if max_indx >= length:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

Most likely categorical columns (from their pandas dtype) get excluded from that qc_vars list, but not for boolean/logical possibly.

**Comment by pcm32** [comment]
The change was introduced at https://github.com/ebi-gene-expression-group/scanpy-scripts/pull/70/files#diff-d4f03c482ed8ddbd6f6e9754d2e42001963362aa3958ee56918f9210747ef2f4R39 to allow negative filtering searches as attempted in #69 .
