### ISSUE TITLE
Missing tsne multicore or not being able to load it

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/scanpy-scripts#57]
When running RunTSNE from a the latest container and having multi-core tSNE activated we get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MulticoreTSNE/__init__.py", line 93, in __init__
    self.C = self.ffi.dlopen(os.path.join(path, sofile))
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 824, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library '/usr/local/lib/python3.6/site-packages/MulticoreTSNE/libtsne_multicore.so': dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scanpy-run-tsne", line 10, in <module>
    sys.exit(TSNE_CMD())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/cmd_utils.py", line 40, in cmd
    func(adata, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/lib/_tsne.py", line 27, in tsne
    sc.tl.tsne(adata, random_state=random_state, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scanpy/tools/_tsne.py", line 95, in tsne
    tsne = TSNE(n_jobs=n_jobs, **params_sklearn)
  File "/usr/local/lib/python3.6/site-packages/MulticoreTSNE/__init__.py", line 95, in __init__
    raise RuntimeError('Cannot find/open tsne_multicore shared library')
RuntimeError: Cannot find/open tsne_multicore shared library
```

This could be either because the library is not there or there is an issue at compilation somewhere which means that this was compiled without -fPIC somewhere. 

Maybe this could help?
https://github.com/conda-forge/multicore-tsne-feedstock/pull/2

https://stackoverflow.com/questions/14892101/cannot-load-any-more-object-with-static-tls

**Comment by pcm32** [comment]
This can be circumvented normally by running by without multicoTSNE of course.

**Comment by nh3** [comment]
Yep, I noticed that too (https://ebi-fg.slack.com/archives/GKM46KMT7/p1571153419015400?thread_ts=1571135685.002800&cid=GKM46KMT7). The issue is with the compiling of the library, which is out of our hands. Hopefully that re-built solves the problem.
