### ISSUE TITLE
h5py error on producing Loom file after FindMarkerGenes

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/scanpy-scripts#60]
When running the export to Loom from FindMarkerGenes, it fails (on the mulled container) with:

```
Cannot export `.obsm` and `.varm` entries to loom.The loom file will lack these fields:
('X_pca',)

Traceback (most recent call last):
  File "/usr/local/bin/scanpy-find-markers", line 10, in <module>
    sys.exit(DIFFEXP_CMD())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/cmd_utils.py", line 51, in cmd
    show_obj=show_obj,
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/cmd_utils.py", line 92, in _write_obj
    write_exchangeable_loom(adata, output_obj, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/exchangeable_loom.py", line 329, in write_exchangeable_loom
    graph_root=lm['/global'],
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/exchangeable_loom.py", line 117, in _h5_write_recursive_dictionary
    graph_root=graph_root,
  File "/usr/local/lib/python3.6/site-packages/scanpy_scripts/exchangeable_loom.py", line 138, in _h5_write_recursive_dictionary
    dataset_root.create_dataset(path, data=data)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1630, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1674, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1587, in h5py.h5t._c_compound
  File "h5py/h5t.pyx", line 1652, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1713, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U50')
```

Will check if this happens as well on direct conda usage

**Comment by nh3** [comment]
This is a known issue. AnnData stores marker genes is a special data structure that cannot be transferred as a dataset to loom easily. It is not handled because the original design goal was to use loom as an intermediate exchangeable format rather than a final storage format, and mark gene set was considered a final product.

**Comment by nh3** [comment]
Yes.
